### ISSUE TITLE
ddanat is broken

### ISSUE THREAD

**Issue by cmungall** [dictyBase/migration-data#6]
Unfortunately ddanat is gone from the OBO library until we can make a release (source ticket: 
https://github.com/OBOFoundry/purl.obolibrary.org/issues/266)

This means you will no longer be able to use it in Noctua

The reason was partially noted in #1 - you have references to obsoletes

```
                Obsolete class DDANAT:0000007 'standing slug' in axiom: SubClassOf(DDANAT:0000019 'prestalk region of the standing slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000007 'standing slug'))
                Obsolete class DDANAT:0000007 'standing slug' in axiom: SubClassOf(DDANAT:0000009 'early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000007 'standing slug'))
                Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000408 'pstA cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0
000021 'prestalk A region of the standing slug'))                Obsolete class DDANAT:0000031 'prestalk O region of the migratory slug' in axiom: SubClassOf(DDANAT:0000407 'pstO cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:
0000031 'prestalk O region of the migratory slug'))
                Obsolete class DDANAT:0000022 'prestalk O region of the standing slug' in axiom: SubClassOf(DDANAT:0000407 'pstO cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0
000022 'prestalk O region of the standing slug'))
                Obsolete class DDANAT:0000024 'prespore region of the standing slug' in axiom: SubClassOf(DDANAT:0000405 'prespore cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT
:0000024 'prespore region of the standing slug'))
                Obsolete class DDANAT:0000008 'migratory slug' in axiom: SubClassOf(DDANAT:0000076 'slime trail' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000008 'migratory slug
'))
                Obsolete class DDANAT:0000026 'peripheral layer of the standing slug' in axiom: SubClassOf(DDANAT:0000046 'peripheral layer of the early culminant' ObjectSomeValuesFr
om(develops_from 'develops_from' DDANAT:0000026 'peripheral layer of the standing slug'))
                Obsolete class DDANAT:0000025 'basal region of the standing slug' in axiom: SubClassOf(DDANAT:0000409 'rearguard cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0
000025 'basal region of the standing slug'))
                Obsolete class DDANAT:0000025 'basal region of the standing slug' in axiom: SubClassOf(DDANAT:0000045 'basal region of the early culminant' ObjectSomeValuesFrom(devel
ops_from 'develops_from' DDANAT:0000025 'basal region of the standing slug'))
                Obsolete class DDANAT:0000024 'prespore region of the standing slug' in axiom: SubClassOf(DDANAT:0000041 'prespore region of the early culminant' ObjectSomeValuesFrom
(develops_from 'develops_from' DDANAT:0000024 'prespore region of the standing slug'))
                Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000039 'prestalk O region of the early culminant' ObjectSomeValues
From(develops_from 'develops_from' DDANAT:0000021 'prestalk A region of the standing slug'))
                Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000038 'prestalk A region of the early culminant' ObjectSomeValues
From(develops_from 'develops_from' DDANAT:0000021 'prestalk A region of the standing slug'))
                Obsolete class DDANAT:0000008 'migratory slug' in axiom: SubClassOf(DDANAT:0000036 'surface sheath of the migratory slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000008 'migratory slug'))
                Obsolete class DDANAT:0000008 'migratory slug' in axiom: SubClassOf(DDANAT:0000035 'peripheral layer of the migratory slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000008 'migratory slug'))
                Obsolete class DDANAT:0000026 'peripheral layer of the standing slug' in axiom: SubClassOf(DDANAT:0000035 'peripheral layer of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000026 'peripheral layer of the standing slug'))
                Obsolete class DDANAT:0000008 'migratory slug' in axiom: SubClassOf(DDANAT:0000034 'posterior region of the migratory slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000008 'migratory slug'))
                Obsolete class DDANAT:0000025 'basal region of the standing slug' in axiom: SubClassOf(DDANAT:0000034 'posterior region of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000025 'basal region of the standing slug'))
                Obsolete class DDANAT:0000024 'prespore region of the standing slug' in axiom: SubClassOf(DDANAT:0000033 'prespore region of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000024 'prespore region of the standing slug'))
                Obsolete class DDANAT:0000008 'migratory slug' in axiom: SubClassOf(DDANAT:0000033 'prespore region of the migratory slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000008 'migratory slug'))
                Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000030 'prestalk A region of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000021 'prestalk A region of the standing slug'))
...
```

**Comment by pfey03** [comment]
Hi @cmungall,

Talked with Sidd and think the culprit is the one obsoleted term in the ddanat that has an active alternative ID DDANAT:0000008. I will destroy this obsolete term to get rid of all. Before I resubmit the updated ontology, want also to fix some stale dictybase references that have gone bad. Will take me a a couple of days and let you when I submit the updated ddanat here.

**Comment by pfey03** [comment]
@cmungall

I uploaded the updated ddanat ontology here. Please grab, I hope this should now work for OWL conversion.

Thanks,
Petra

**Comment by cmungall** [comment]
OK, everything should be fine when the build runs ~midnight

if these work

 * http://purl.obolibrary.org/obo/ddanat.obo
 * http://purl.obolibrary.org/obo/ddanat.owl

then the ticket can be closed

(btw, looks like you wholesale deleted DDANAT:0000430 - generally you want to keep some record around)

**Comment by pfey03** [comment]
> (btw, looks like you wholesale deleted DDANAT:0000430 - generally you want to keep some record around)


wow, how did that the f happen? Let me check and fix!

**Comment by pfey03** [comment]
Oh of course, it is the one obsoleted term and I deleted that whole sale. Really much better than keeping it around and doing hard fix to delete alt ID

**Comment by cmungall** [comment]
Sorry, the ontology is still broken:

		Obsolete class DDANAT:0000006 'tipped mound' in axiom: SubClassOf(DDANAT:0000018 'surface sheath of the tipped mound' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000006 'tipped mound'))
		Obsolete class DDANAT:0000006 'tipped mound' in axiom: SubClassOf(DDANAT:0000017 'prespore region of the tipped mound' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000006 'tipped mound'))
		Obsolete class DDANAT:0000006 'tipped mound' in axiom: SubClassOf(DDANAT:0000016 'prestalk region of the tipped mound' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000006 'tipped mound'))
		Obsolete class DDANAT:0000003 'aggregation territory' in axiom: SubClassOf(DDANAT:0000013 'stream' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000003 'aggregation territory'))
		Obsolete class DDANAT:0000009 'early culminant' in axiom: SubClassOf(DDANAT:0000010 'mid culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000009 'early culminant'))
		Obsolete class DDANAT:0000003 'aggregation territory' in axiom: SubClassOf(DDANAT:0000004 'loose aggregate' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000003 'aggregation territory'))
		Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000408 'pstA cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000021 'prestalk A region of the standing slug'))
		Obsolete class DDANAT:0000031 'prestalk O region of the migratory slug' in axiom: SubClassOf(DDANAT:0000407 'pstO cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000031 'prestalk O region of the migratory slug'))
		Obsolete class DDANAT:0000022 'prestalk O region of the standing slug' in axiom: SubClassOf(DDANAT:0000407 'pstO cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000022 'prestalk O region of the standing slug'))
		Obsolete class DDANAT:0000024 'prespore region of the standing slug' in axiom: SubClassOf(DDANAT:0000405 'prespore cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000024 'prespore region of the standing slug'))
		Obsolete class DDANAT:0000003 'aggregation territory' in axiom: SubClassOf(DDANAT:0000403 'aggregate cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000003 'aggregation territory'))
		Obsolete class DDANAT:0000009 'early culminant' in axiom: SubClassOf(DDANAT:0000046 'peripheral layer of the early culminant' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000009 'early culminant'))
		Obsolete class DDANAT:0000026 'peripheral layer of the standing slug' in axiom: SubClassOf(DDANAT:0000046 'peripheral layer of the early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000026 'peripheral layer of the standing slug'))
		Obsolete class DDANAT:0000009 'early culminant' in axiom: SubClassOf(DDANAT:0000047 'surface sheath of the early culminant' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000009 'early culminant'))
		Obsolete class DDANAT:0000025 'basal region of the standing slug' in axiom: SubClassOf(DDANAT:0000409 'rearguard cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000025 'basal region of the standing slug'))
		Obsolete class DDANAT:0000009 'early culminant' in axiom: SubClassOf(DDANAT:0000045 'basal region of the early culminant' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000009 'early culminant'))
		Obsolete class DDANAT:0000025 'basal region of the standing slug' in axiom: SubClassOf(DDANAT:0000045 'basal region of the early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000025 'basal region of the standing slug'))
		Obsolete class DDANAT:0000009 'early culminant' in axiom: SubClassOf(DDANAT:0000043 'stalk tube of the early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000009 'early culminant'))
		Obsolete class DDANAT:0000009 'early culminant' in axiom: SubClassOf(DDANAT:0000041 'prespore region of the early culminant' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000009 'early culminant'))
		Obsolete class DDANAT:0000024 'prespore region of the standing slug' in axiom: SubClassOf(DDANAT:0000041 'prespore region of the early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000024 'prespore region of the standing slug'))
		Obsolete class DDANAT:0000007 'standing slug' in axiom: SubClassOf(DDANAT:0000008 'migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000007 'standing slug'))
		Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000039 'prestalk O region of the early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000021 'prestalk A region of the standing slug'))
		Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000038 'prestalk A region of the early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000021 'prestalk A region of the standing slug'))
		Obsolete class DDANAT:0000019 'prestalk region of the standing slug' in axiom: SubClassOf(DDANAT:0000037 'prestalk region of the early culminant' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000019 'prestalk region of the standing slug'))
		Obsolete class DDANAT:0000009 'early culminant' in axiom: SubClassOf(DDANAT:0000037 'prestalk region of the early culminant' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000009 'early culminant'))
		Obsolete class DDANAT:0000026 'peripheral layer of the standing slug' in axiom: SubClassOf(DDANAT:0000035 'peripheral layer of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000026 'peripheral layer of the standing slug'))
		Obsolete class DDANAT:0000025 'basal region of the standing slug' in axiom: SubClassOf(DDANAT:0000034 'posterior region of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000025 'basal region of the standing slug'))
		Obsolete class DDANAT:0000024 'prespore region of the standing slug' in axiom: SubClassOf(DDANAT:0000033 'prespore region of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000024 'prespore region of the standing slug'))
		Obsolete class DDANAT:0000021 'prestalk A region of the standing slug' in axiom: SubClassOf(DDANAT:0000030 'prestalk A region of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000021 'prestalk A region of the standing slug'))
		Obsolete class DDANAT:0000019 'prestalk region of the standing slug' in axiom: SubClassOf(DDANAT:0000028 'prestalk region of the migratory slug' ObjectSomeValuesFrom(develops_from 'develops_from' DDANAT:0000019 'prestalk region of the standing slug'))
		Obsolete class DDANAT:0000007 'standing slug' in axiom: SubClassOf(DDANAT:0000027 'surface sheath of the standing slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000007 'standing slug'))
		Obsolete class DDANAT:0000019 'prestalk region of the standing slug' in axiom: SubClassOf(DDANAT:0000023 'prestalk AB core region of the standing slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000019 'prestalk region of the standing slug'))
		Obsolete class DDANAT:0000019 'prestalk region of the standing slug' in axiom: SubClassOf(DDANAT:0000020 'tip-organizer of the standing slug' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000019 'prestalk region of the standing slug'))
		Obsolete class DDANAT:0000026 'peripheral layer of the standing slug' in axiom: SubClassOf(DDANAT:0000095 'peripheral layer cell' ObjectSomeValuesFrom(part_of 'part of' DDANAT:0000026 'peripheral layer of the standing slug'))

**Comment by pfey03** [comment]
Could you specify? Sorry this is all Pascale heritage and I don't know. Are the obsolete terms children of active terms and is that not allowed?

**Comment by cmungall** [comment]
ok sorry false positive. You fixed this. However, we weren't picking up the new version as it gets lost because it doesn't have an ontology tag

click merge here and all will be good:
https://github.com/dictyBase/migration-data/pull/7

**Comment by pfey03** [comment]
Done! Good night and good luck!

**Comment by cmungall** [comment]
OK, I misspoke when I said it was a false positive. There is in fact an issue. Look at the alt_id in the stanza below:

```
[Term]
id: DDANAT:0000407
name: pstO cell
alt_id: DDANAT:0000006
def: "Cell that is undergoing differentiation to become a stalk cell. pstO cells express ecmA at a very low level and are located at the posterior half of the prestalk zone. Expresses ecmA from the distal region of its promoter (ecmO)." [DDB:pg]
synonym: "prestalk O cell" RELATED []
xref: CL:0000279 "Cell Line Ontology"
is_a: DDANAT:0000406 ! prestalk cell
relationship: part_of DDANAT:0000004 ! loose aggregate
relationship: part_of DDANAT:0000005 ! mound
relationship: part_of DDANAT:0000022 ! prestalk O region of the standing slug
relationship: part_of DDANAT:0000031 ! prestalk O region of the migratory slug
relationship: part_of DDANAT:0000039 ! prestalk O region of the early culminant
relationship: part_of DDANAT:0000050 ! prestalk O region of the mid culminant
relationship: part_of DDANAT:0000102 ! prestalk O region of the tipped mound
```

You have merged in (DDANAT:0000006), but it's still referenced 

cc @pgaudet

**Comment by pfey03** [comment]
hi Chris,
Yeah, no idea why DDANAT:0000006 - tipped mound, is an alt_ID for DDANAT:0000407. I cannot unmerge or fix this in Oboedit, it seems. Should I do a hard fix to take the alt_ID out?
Thanks,
Petra

**Comment by pgaudet** [comment]
Hi @cmungall , @pfey03 , 

I looked at the ontolopy in protege and I don't understand what's going on. The terms listed above by Chris do appear obsolete in protege but not in the original obo file that I downloaded here: 
https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_anatomy.obo

@cmungall , any idea why protege would interpret these classes as obsolete ? I couldn't see anything special about them. 

Thanks, 
Pascale

**Comment by cmungall** [comment]
alt_ids are treated as obsoletions

**Comment by pfey03** [comment]
Well, the only solution I see is to hard hack it and take the alt_id out from DDANAT:0000407. If that's ok by both of you I'll do tomorrow and submit the new to git.

**Comment by pfey03** [comment]
@cmungall, the ontology is now updated, let us know if that's ok now.
Thanks @pgaudet for your help!

**Comment by cmungall** [comment]
Many Thanks!!! Test run worked. ddanat should be updated on OBO tonight!

**Comment by pfey03** [comment]
Great! Thanks both of you!
